# Generated by Django 5.2.4 on 2026-07-19 07:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_key', models.CharField(max_length=512, unique=True)),
                ('filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=128)),
                ('size_bytes', models.BigIntegerField()),
                ('checksum_sha256', models.CharField(db_index=True, max_length=64)),
                ('scan_status', models.CharField(choices=[('pending', 'Pending'), ('clean', 'Clean'), ('infected', 'Infected'), ('error', 'Scan error')], default='pending', max_length=16)),
                ('scan_signature', models.CharField(blank=True, max_length=128)),
                ('scanned_at', models.DateTimeField(blank=True, null=True)),
                ('quarantine_path', models.CharField(blank=True, max_length=512)),
                ('uploaded_by_subject', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'file_attachment',
                'ordering': ('-uploaded_at',),
            },
        ),
        migrations.CreateModel(
            name='AttachmentAccessLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_subject', models.CharField(max_length=255)),
                ('ip_address', models.GenericIPAddressField(null=True)),
                ('user_agent', models.CharField(blank=True, max_length=512)),
                ('at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'file_attachment_access',
                'ordering': ('-at',),
            },
        ),
    ]
