# Generated by Django 5.2.4 on 2026-07-19 06:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_key', models.CharField(max_length=512)),
                ('checksum_sha256', models.CharField(max_length=64)),
                ('size_bytes', models.BigIntegerField()),
                ('content_type', models.CharField(max_length=128)),
                ('scan_status', models.CharField(default='pending', max_length=16)),
            ],
            options={
                'db_table': 'attachment',
            },
        ),
    ]
