# Generated by Django 5.2.4 on 2026-07-19 07:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(max_length=16)),
                ('recipient', models.CharField(max_length=255)),
                ('template_key', models.CharField(max_length=128)),
                ('payload', models.JSONField()),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'notification',
            },
        ),
    ]
