# Generated by Django 5.2.4 on 2026-07-19 06:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=128, unique=True)),
                ('value', models.JSONField()),
                ('version', models.PositiveIntegerField(default=1)),
            ],
            options={
                'db_table': 'configitem',
            },
        ),
    ]
