# Generated by Django 5.2.4 on 2026-07-19 08:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tickets', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsappAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number_id', models.CharField(max_length=64, unique=True)),
                ('display_name', models.CharField(max_length=128)),
                ('domain', models.CharField(choices=[('operational', 'Operational'), ('it', 'IT')], max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('access_token', models.CharField(blank=True, max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'whatsapp_account',
            },
        ),
        migrations.CreateModel(
            name='WhatsappMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_number', models.CharField(blank=True, max_length=32)),
                ('to_number', models.CharField(blank=True, max_length=32)),
                ('direction', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], max_length=16)),
                ('body', models.TextField()),
                ('external_message_id', models.CharField(blank=True, db_index=True, max_length=128)),
                ('delivery_status', models.CharField(blank=True, max_length=32)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='whatsapp.whatsappaccount')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_messages', to='tickets.ticket')),
            ],
            options={
                'db_table': 'whatsapp_message',
                'ordering': ('-created_at',),
            },
        ),
    ]
