# Generated by Django 5.2.4 on 2026-07-19 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsappmessage',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='whatsapp.whatsappaccount'),
        ),
    ]
