# Generated by Django 5.2.4 on 2026-07-28

from django.db import migrations, models
from django.db.models import Count


def clear_duplicate_external_message_ids(apps, schema_editor):
    """Preserve every historical row while choosing one canonical provider ID."""
    whatsapp_message = apps.get_model("whatsapp", "WhatsappMessage")
    duplicate_ids = (
        whatsapp_message.objects.exclude(external_message_id="")
        .values("external_message_id")
        .annotate(row_count=Count("id"))
        .filter(row_count__gt=1)
        .values_list("external_message_id", flat=True)
    )
    for external_message_id in duplicate_ids.iterator():
        duplicate_rows = whatsapp_message.objects.filter(
            external_message_id=external_message_id
        ).order_by("created_at", "id")
        canonical_id = duplicate_rows.values_list("id", flat=True).first()
        duplicate_rows.exclude(id=canonical_id).update(external_message_id="")


class Migration(migrations.Migration):

    dependencies = [
        ("whatsapp", "0002_alter_whatsappmessage_account"),
    ]

    operations = [
        migrations.AddField(
            model_name="whatsappaccount",
            name="business_id",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.RunPython(
            clear_duplicate_external_message_ids,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name="whatsappmessage",
            constraint=models.UniqueConstraint(
                condition=models.Q(("external_message_id", ""), _negated=True),
                fields=("external_message_id",),
                name="uniq_whatsapp_external_message_when_set",
            ),
        ),
    ]
