# Generated by Django 5.2.4 on 2026-07-19 07:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_subject', models.CharField(db_index=True, max_length=255)),
                ('action', models.CharField(max_length=128)),
                ('object_type', models.CharField(max_length=64)),
                ('object_id', models.CharField(max_length=64)),
                ('ip_address', models.GenericIPAddressField(null=True)),
                ('payload_hash', models.CharField(max_length=64)),
                ('occurred_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'auditevent',
            },
        ),
    ]
