# Generated by Django 5.2.4 on 2026-07-27 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditevent',
            name='payload',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
