# Generated by Django 5.2.4 on 2026-07-19 08:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tickets', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeArticle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=64, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('audience', models.CharField(choices=[('public', 'Public'), ('internal_op', 'Internal — Operational'), ('internal_it', 'Internal — IT'), ('restricted', 'Restricted')], max_length=24)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_review', 'In review'), ('published', 'Published'), ('retired', 'Retired')], default='draft', max_length=16)),
                ('domain', models.CharField(choices=[('operational', 'Operational'), ('it', 'IT')], max_length=16)),
                ('language', models.CharField(default='en', max_length=8)),
                ('version', models.PositiveIntegerField(default=1)),
                ('owner_subject', models.CharField(max_length=255)),
                ('approved_by_subject', models.CharField(blank=True, max_length=255)),
                ('last_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('next_review_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'knowledge_article',
                'indexes': [models.Index(fields=['audience', 'status'], name='knowledge_a_audienc_0c200b_idx')],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeUsageLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_subject', models.CharField(blank=True, max_length=255)),
                ('used_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='knowledge.knowledgearticle')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.ticket')),
            ],
            options={
                'db_table': 'knowledge_usage',
            },
        ),
    ]
