# Generated by Django 5.2.4 on 2026-07-19 07:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=128)),
                ('domain', models.CharField(choices=[('operational', 'Operational'), ('it', 'IT')], max_length=16)),
                ('is_terminal', models.BooleanField(default=False)),
                ('is_initial', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('public_label', models.CharField(blank=True, help_text='Friendly label exposed to the requester (PRD §29.5)', max_length=128)),
            ],
            options={
                'db_table': 'workflow_status',
                'ordering': ('domain', 'order'),
                'constraints': [models.UniqueConstraint(fields=('domain', 'code'), name='uniq_status_domain_code')],
            },
        ),
        migrations.CreateModel(
            name='TransitionHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_subject', models.CharField(db_index=True, max_length=255)),
                ('reason', models.TextField(blank=True)),
                ('occurred_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('from_status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='workflow.status')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transition_history', to='tickets.ticket')),
                ('to_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='workflow.status')),
            ],
            options={
                'db_table': 'workflow_transition_history',
                'ordering': ('-occurred_at',),
            },
        ),
        migrations.CreateModel(
            name='Transition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('domain', models.CharField(max_length=16)),
                ('name', models.CharField(max_length=128)),
                ('required_role', models.CharField(blank=True, max_length=64)),
                ('required_fields', models.JSONField(blank=True, default=list)),
                ('sets_resolution', models.BooleanField(default=False, help_text='If true, the transition requires a resolution code + summary (FR-022)')),
                ('is_active', models.BooleanField(default=True)),
                ('from_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions_from', to='workflow.status')),
                ('to_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions_to', to='workflow.status')),
            ],
            options={
                'db_table': 'workflow_transition',
                'unique_together': {('domain', 'from_status', 'to_status')},
            },
        ),
    ]
