# Generated by Django 5.2.4 on 2026-07-19 08:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('description', models.TextField(blank=True)),
                ('trigger', models.CharField(choices=[('ticket.created', 'Ticket created'), ('ticket.transitioned', 'Ticket transitioned'), ('sla.at_risk', 'SLA at risk'), ('sla.breached', 'SLA breached'), ('ticket.unassigned', 'Ticket unassigned')], max_length=32)),
                ('conditions', models.JSONField(blank=True, default=dict)),
                ('action', models.CharField(choices=[('assign_user', 'Assign user'), ('set_priority', 'Set priority'), ('notify', 'Notify'), ('add_note', 'Add note')], max_length=32)),
                ('action_params', models.JSONField(blank=True, default=dict)),
                ('priority', models.PositiveIntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'automation_rule',
                'ordering': ('priority', 'name'),
            },
        ),
        migrations.CreateModel(
            name='AutomationExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('aggregate', models.CharField(max_length=64)),
                ('aggregate_id', models.CharField(max_length=64)),
                ('success', models.BooleanField()),
                ('detail', models.TextField(blank=True)),
                ('executed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='automation.automationrule')),
            ],
            options={
                'db_table': 'automation_execution',
            },
        ),
    ]
