# Generated by Django 5.2.4 on 2026-07-27 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("identity_access", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="keycloak_groups",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
