# Generated by Django 5.2.16 on 2026-08-19 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity_access', '0003_internal_staff_roles'),
        ('organisations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='based_officers', to='organisations.office'),
        ),
        migrations.AddField(
            model_name='user',
            name='station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stationed_officers', to='organisations.servicelocation'),
        ),
    ]
