# Generated by Django 5.2.4 on 2026-07-19 07:21

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessCalendar',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('timezone', models.CharField(default='Africa/Mbabane', max_length=64)),
                ('weekday_hours', models.JSONField(default=dict, help_text="e.g. {'1': [{'start': '08:00', 'end': '17:00'}]}")),
                ('holidays', models.JSONField(default=list)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sla_calendar',
            },
        ),
        migrations.CreateModel(
            name='SlaInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(max_length=32)),
                ('state', models.CharField(choices=[('active', 'Active'), ('paused_requester', 'Paused — requester'), ('paused_internal', 'Paused — internal'), ('paused_it', 'Paused — IT'), ('met', 'Met'), ('breached', 'Breached'), ('cancelled', 'Cancelled')], default='active', max_length=24)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('due_at', models.DateTimeField()),
                ('consumed_business_seconds', models.PositiveIntegerField(default=0)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('breached_at', models.DateTimeField(blank=True, null=True)),
                ('breach_reason', models.TextField(blank=True)),
                ('last_evaluated_at', models.DateTimeField(blank=True, null=True)),
                ('warn_notified_at', models.DateTimeField(blank=True, null=True)),
                ('escalation_notified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sla_instance',
            },
        ),
        migrations.CreateModel(
            name='SlaPauseHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state', models.CharField(max_length=24)),
                ('reason', models.CharField(max_length=128)),
                ('actor_subject', models.CharField(blank=True, max_length=255)),
                ('at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'sla_pause_history',
                'ordering': ('-at',),
            },
        ),
        migrations.CreateModel(
            name='SlaPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('domain', models.CharField(choices=[('operational', 'Operational'), ('it', 'IT')], max_length=16)),
                ('priority', models.CharField(max_length=8)),
                ('acknowledgement_minutes', models.PositiveIntegerField(default=0)),
                ('first_response_minutes', models.PositiveIntegerField()),
                ('update_interval_minutes', models.PositiveIntegerField()),
                ('resolution_minutes', models.PositiveIntegerField()),
                ('warn_at_percent', models.PositiveIntegerField(default=75)),
                ('escalation_percent', models.PositiveIntegerField(default=90)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sla_policy',
            },
        ),
    ]
