# Generated by Django 5.2.4 on 2026-07-19 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sla', '0001_initial'),
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slainstance',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sla_instances', to='tickets.ticket'),
        ),
        migrations.AddField(
            model_name='slapausehistory',
            name='instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pause_history', to='sla.slainstance'),
        ),
        migrations.AddField(
            model_name='slapolicy',
            name='calendar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='policies', to='sla.businesscalendar'),
        ),
        migrations.AddField(
            model_name='slainstance',
            name='policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='sla.slapolicy'),
        ),
        migrations.AlterUniqueTogether(
            name='slapolicy',
            unique_together={('domain', 'priority', 'name')},
        ),
        migrations.AddIndex(
            model_name='slainstance',
            index=models.Index(fields=['state', 'due_at'], name='sla_instanc_state_13414e_idx'),
        ),
        migrations.AddIndex(
            model_name='slainstance',
            index=models.Index(fields=['ticket', 'kind'], name='sla_instanc_ticket__b4bebd_idx'),
        ),
    ]
