# Generated by Django 5.2.4 on 2026-07-30 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sla', '0004_backfill_paused_remaining_business_seconds'),
    ]

    operations = [
        migrations.AddField(
            model_name='slainstance',
            name='remaining_business_microseconds',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
