# Generated by Django 5.2.4 on 2026-07-19 07:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('domain', models.CharField(choices=[('operational', 'Operational'), ('it', 'IT')], max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'catalogue_service',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='RequestType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('default_priority', models.CharField(default='P3', max_length=8)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_types', to='catalogue.service')),
            ],
            options={
                'db_table': 'catalogue_request_type',
                'unique_together': {('service', 'code')},
            },
        ),
        migrations.CreateModel(
            name='CustomFieldDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=64)),
                ('label', models.CharField(max_length=255)),
                ('kind', models.CharField(choices=[('text', 'Text'), ('textarea', 'Textarea'), ('select', 'Select'), ('multiselect', 'Multiselect'), ('date', 'Date'), ('number', 'Number'), ('boolean', 'Boolean')], max_length=16)),
                ('required', models.BooleanField(default=False)),
                ('choices', models.JSONField(blank=True, default=list)),
                ('help_text', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('request_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='catalogue.requesttype')),
            ],
            options={
                'db_table': 'catalogue_custom_field',
                'ordering': ('order', 'key'),
                'unique_together': {('request_type', 'key')},
            },
        ),
    ]
