# Generated by Django 5.2.4 on 2026-07-19 08:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tickets', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mailbox',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('address', models.EmailField(max_length=254, unique=True)),
                ('domain', models.CharField(choices=[('operational', 'Operational'), ('it', 'IT')], max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('provider', models.CharField(default='generic', max_length=32)),
                ('secret', models.CharField(blank=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'email_mailbox',
                'ordering': ('address',),
            },
        ),
        migrations.CreateModel(
            name='EmailDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('to_address', models.EmailField(max_length=254)),
                ('from_address', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=512)),
                ('body_text', models.TextField()),
                ('message_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('in_reply_to', models.CharField(blank=True, max_length=255)),
                ('references', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('bounced', 'Bounced')], default='pending', max_length=16)),
                ('error', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_deliveries', to='tickets.ticketmessage')),
            ],
            options={
                'db_table': 'email_delivery',
                'ordering': ('-created_at',),
            },
        ),
    ]
