# Generated by Django 5.2.4 on 2026-07-28

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("email_channel", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailWebhookEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("event_id", models.CharField(max_length=255, unique=True)),
                ("event_type", models.CharField(max_length=32)),
                ("message_id", models.CharField(blank=True, max_length=255)),
                ("received_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "email_webhook_event",
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("message_id", ""), _negated=True),
                        fields=("event_type", "message_id"),
                        name="uniq_email_webhook_type_message_when_set",
                    )
                ],
            },
        ),
    ]
