# Generated by Django 5.2.4 on 2026-07-19 07:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0001_initial'),
        ('contacts', '0001_initial'),
        ('organisations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OutboxEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('aggregate', models.CharField(db_index=True, max_length=64)),
                ('aggregate_id', models.CharField(db_index=True, max_length=64)),
                ('event_type', models.CharField(db_index=True, max_length=128)),
                ('payload', models.JSONField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], db_index=True, default='pending', max_length=16)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('next_attempt_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ticket_outbox',
            },
        ),
        migrations.CreateModel(
            name='TicketLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('parent', 'Parent of'), ('child', 'Child of'), ('related', 'Related to'), ('duplicate_of', 'Duplicate of'), ('blocked_by', 'Blocked by'), ('blocks', 'Blocks'), ('merged_from', 'Merged from'), ('it_child', 'IT child of operational')], max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ticket_link',
            },
        ),
        migrations.CreateModel(
            name='TicketMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('direction', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], max_length=16)),
                ('author_subject', models.CharField(blank=True, max_length=255)),
                ('author_label', models.CharField(blank=True, max_length=255)),
                ('body_text', models.TextField()),
                ('body_html', models.TextField(blank=True)),
                ('body_html_sanitized', models.TextField(blank=True)),
                ('template_key', models.CharField(blank=True, max_length=128)),
                ('template_version', models.CharField(blank=True, max_length=32)),
                ('external_message_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('delivery_status', models.CharField(blank=True, max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'ticket_message',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='TicketNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('author_subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'ticket_note',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='Watcher',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ticket_watcher',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(db_index=True, max_length=32, unique=True)),
                ('domain', models.CharField(choices=[('operational', 'Operational'), ('it', 'IT')], max_length=16)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('P1', 'P1 Critical'), ('P2', 'P2 High'), ('P3', 'P3 Normal'), ('P4', 'P4 Low')], default='P3', max_length=8)),
                ('channel', models.CharField(choices=[('call', 'Call centre'), ('walk_in', 'Walk-in'), ('web', 'Public web form'), ('email', 'Email'), ('internal', 'Internal referral'), ('whatsapp', 'WhatsApp'), ('monitoring', 'Monitoring')], max_length=16)),
                ('source_account', models.CharField(blank=True, max_length=255)),
                ('team', models.CharField(blank=True, max_length=128)),
                ('confidentiality', models.CharField(choices=[('normal', 'Normal'), ('sensitive', 'Sensitive'), ('restricted', 'Restricted')], default='normal', max_length=16)),
                ('matter_reference', models.CharField(blank=True, db_index=True, max_length=128)),
                ('external_message_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('waiting_reason', models.CharField(blank=True, max_length=64)),
                ('blocked_reason', models.TextField(blank=True)),
                ('resolution_code', models.CharField(blank=True, max_length=64)),
                ('resolution_summary', models.TextField(blank=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('custom_fields', models.JSONField(blank=True, default=dict)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('first_responded_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('reopened_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL)),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='organisations.office')),
                ('organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='contacts.organisation')),
                ('queue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='organisations.servicelocation')),
                ('request_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='catalogue.requesttype')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_tickets', to='contacts.contact')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='catalogue.service')),
            ],
            options={
                'db_table': 'ticket',
                'ordering': ('-created_at',),
            },
        ),
    ]
