# Generated by Django 5.2.4 on 2026-07-19 07:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tickets', '0001_initial'),
        ('workflow', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='workflow.status'),
        ),
        migrations.AddField(
            model_name='ticketlink',
            name='from_ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links_from', to='tickets.ticket'),
        ),
        migrations.AddField(
            model_name='ticketlink',
            name='to_ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links_to', to='tickets.ticket'),
        ),
        migrations.AddField(
            model_name='ticketmessage',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='tickets.ticket'),
        ),
        migrations.AddField(
            model_name='ticketnote',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='tickets.ticket'),
        ),
        migrations.AddField(
            model_name='watcher',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchers', to='tickets.ticket'),
        ),
        migrations.AddField(
            model_name='watcher',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watching', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['domain', 'status'], name='ticket_domain_bd5590_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['domain', 'priority'], name='ticket_domain_cf97fc_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['assignee', 'status'], name='ticket_assigne_0dfca4_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['requester', '-created_at'], name='ticket_request_05f4b2_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['office', 'status'], name='ticket_office__3a523d_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['created_at'], name='ticket_created_807d9e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='ticketlink',
            unique_together={('from_ticket', 'to_ticket', 'kind')},
        ),
        migrations.AlterUniqueTogether(
            name='watcher',
            unique_together={('ticket', 'user')},
        ),
    ]
