# Generated by Django 5.2.4 on 2026-07-27 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_ticket_legal_hold_ticket_legal_hold_expires_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='next_action',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='ticket',
            name='next_action_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
