# Generated by Django 5.2.4 on 2026-07-30 13:31

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_ticket_next_action_ticket_next_action_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketCustodyEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence', models.PositiveBigIntegerField()),
                ('event_type', models.CharField(choices=[('created', 'Created'), ('assigned', 'Assigned'), ('reassigned', 'Transferred / reassigned'), ('unassigned', 'Unassigned'), ('queue_changed', 'Queue changed'), ('escalated', 'Escalated'), ('status_changed', 'Status changed'), ('reopened', 'Reopened'), ('closed', 'Closed')], max_length=32)),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('actor_kind', models.CharField(choices=[('user', 'User'), ('system', 'System')], max_length=16)),
                ('actor_subject', models.CharField(max_length=255)),
                ('actor_display_name', models.CharField(max_length=255)),
                ('source_process', models.CharField(max_length=128)),
                ('source_record_type', models.CharField(blank=True, max_length=64)),
                ('source_record_id', models.CharField(blank=True, max_length=64)),
                ('previous_owner', models.JSONField(blank=True, null=True)),
                ('new_owner', models.JSONField(blank=True, null=True)),
                ('previous_queue', models.JSONField(blank=True, null=True)),
                ('new_queue', models.JSONField(blank=True, null=True)),
                ('previous_status', models.JSONField(blank=True, null=True)),
                ('new_status', models.JSONField(blank=True, null=True)),
                ('previous_designations', models.JSONField(blank=True, default=list)),
                ('new_designations', models.JSONField(blank=True, default=list)),
                ('previous_team_labels', models.JSONField(blank=True, default=list)),
                ('new_team_labels', models.JSONField(blank=True, default=list)),
                ('reason', models.TextField(blank=True)),
                ('previous_hash', models.CharField(blank=True, max_length=64)),
                ('event_hash', models.CharField(max_length=64)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custody_events', to='tickets.ticket')),
            ],
            options={
                'base_manager_name': 'objects',
                'db_table': 'ticket_custody_event',
                'ordering': ('sequence', 'id'),
                'constraints': [models.UniqueConstraint(fields=('ticket', 'sequence'), name='uniq_ticket_custody_sequence')],
            },
        ),
    ]
