# Generated by Django 5.2.4 on 2026-07-30 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_ticketcustodyevent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticketcustodyevent',
            options={'base_manager_name': 'objects', 'ordering': ('sequence', 'id')},
        ),
    ]
